from PyQt5 import QtCore, QtGui, QtWidgets

class AdminLogin:
    def setup_ALoginUi(self, AdminLogin):
        AdminLogin.setObjectName("AdminLogin")
        AdminLogin.resize(1314, 644)
        AdminLogin.setStyleSheet("font: 16pt \"Modern No. 20\";color:green;padding:6px 16px;background-color:#f8f8f6;")
        self.centralwidget = QtWidgets.QWidget(AdminLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pic_frame = QtWidgets.QFrame(self.centralwidget)
        self.pic_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pic_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pic_frame.setObjectName("pic_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pic_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pic_label = QtWidgets.QLabel(self.pic_frame)
        self.pic_label.setText("")
        self.pic_label.setPixmap(QtGui.QPixmap("./icons/logo.png"))
        self.pic_label.setObjectName("pic_label")
        self.verticalLayout.addWidget(self.pic_label)
        self.horizontalLayout_2.addWidget(self.pic_frame)
        self.details = QtWidgets.QFrame(self.centralwidget)
        self.details.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.details.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.details.setFrameShadow(QtWidgets.QFrame.Raised)
        self.details.setObjectName("details")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.details)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(487, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.welcome_message = QtWidgets.QLabel(self.details)
        self.welcome_message.setStyleSheet("font: 36pt \"Modern No. 20\";")
        self.welcome_message.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_message.setObjectName("welcome_message")
        self.verticalLayout_2.addWidget(self.welcome_message)
        spacerItem1 = QtWidgets.QSpacerItem(76, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.enter_details = QtWidgets.QLabel(self.details)
        self.enter_details.setStyleSheet("font: 26pt \"Modern No. 20\";")
        self.enter_details.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_details.setObjectName("enter_details")
        self.verticalLayout_2.addWidget(self.enter_details)
        self.username = QtWidgets.QLabel(self.details)
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.user_edit = QtWidgets.QLineEdit(self.details)
        self.user_edit.setStyleSheet("border:1px solid black;border-radius:10px;padding:5px 10px")
        self.user_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_edit.setObjectName("user_edit")
        self.verticalLayout_2.addWidget(self.user_edit)
        self.password = QtWidgets.QLabel(self.details)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.password_edit = QtWidgets.QLineEdit(self.details)
        self.password_edit.setStyleSheet("border:1px solid black;border-radius:10px;padding:5px 10px")
        self.password_edit.setObjectName("password_edit")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_2.addWidget(self.password_edit)
        self.submit_button_frame = QtWidgets.QFrame(self.details)
        self.submit_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_button_frame.setObjectName("submit_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.submit_button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submit_button = QtWidgets.QPushButton(self.submit_button_frame)
        self.submit_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.submit_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_button.setAutoFillBackground(False)
        self.submit_button.setStyleSheet("font: 20pt \"Modern No. 20\";color:green;padding:3px 20px;border:2px solid darkgreen;border-radius:5px;")
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.authenticateLogin)
        self.horizontalLayout.addWidget(self.submit_button)
        self.verticalLayout_2.addWidget(self.submit_button_frame)
        self.horizontalLayout_2.addWidget(self.details)
        AdminLogin.setCentralWidget(self.centralwidget)
        AdminLogin.setWindowTitle("Admin Login")
        self.retranslateUi(AdminLogin)
        QtCore.QMetaObject.connectSlotsByName(AdminLogin)

    def retranslateUi(self, AdminLogin):
        _translate = QtCore.QCoreApplication.translate
        self.welcome_message.setText(_translate("AdminLogin", "Eternus Banking Admin Login"))
        self.enter_details.setText(_translate("AdminLogin", "Enter the following details to sign in."))
        self.username.setText(_translate("AdminLogin", "User Name: "))
        self.user_edit.setPlaceholderText(_translate("AdminLogin", "..."))
        self.password.setText(_translate("AdminLogin", "Password: "))
        self.password_edit.setPlaceholderText(_translate("AdminLogin", "..."))
        self.submit_button.setText(_translate("AdminLogin", "Submit"))
        

    def authenticateLogin(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminLogin = QtWidgets.QMainWindow()
    ui = Ui_AdminLogin()
    ui.setupUi(AdminLogin)
    AdminLogin.show()
    sys.exit(app.exec_())
