
yello = 123
for i in range(2):
    exec("""
print(yello)""")
    
    
      self.transaction_1 = QtWidgets.QFrame(self.transactions)
        self.transaction_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transaction_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transaction_1.setObjectName("transaction_1")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.transaction_1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.amount_1 = QtWidgets.QLabel(self.transaction_1)
        self.amount_1.setObjectName("amount_1")
        self.horizontalLayout_19.addWidget(self.amount_1)
        self.details_1 = QtWidgets.QFrame(self.transaction_1)
        self.details_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.details_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.details_1.setObjectName("details_1")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.details_1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.withdrawn_1 = QtWidgets.QLabel(self.details_1)
        self.withdrawn_1.setObjectName("withdrawn_1")
        self.verticalLayout_25.addWidget(self.withdrawn_1)
        self.date_1 = QtWidgets.QLabel(self.details_1)
        self.date_1.setObjectName("date_1")
        self.verticalLayout_25.addWidget(self.date_1)
        self.horizontalLayout_19.addWidget(self.details_1)
        self.verticalLayout_21.addWidget(self.transaction_1)
        self.transaction_2 = QtWidgets.QFrame(self.transactions)
        self.transaction_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transaction_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transaction_2.setObjectName("transaction_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.transaction_2)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.amount_2 = QtWidgets.QLabel(self.transaction_2)
        self.amount_2.setObjectName("amount_2")
        self.horizontalLayout_18.addWidget(self.amount_2)
        self.details_2 = QtWidgets.QFrame(self.transaction_2)
        self.details_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.details_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.details_2.setObjectName("details_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.details_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.withdraw_2 = QtWidgets.QLabel(self.details_2)
        self.withdraw_2.setObjectName("withdraw_2")
        self.verticalLayout_24.addWidget(self.withdraw_2)
        self.date_2 = QtWidgets.QLabel(self.details_2)
        self.date_2.setObjectName("date_2")
        self.verticalLayout_24.addWidget(self.date_2)
        self.horizontalLayout_18.addWidget(self.details_2)
        self.verticalLayout_21.addWidget(self.transaction_2)
        self.transaction_3 = QtWidgets.QFrame(self.transactions)
        self.transaction_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transaction_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transaction_3.setObjectName("transaction_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.transaction_3)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.amount_3 = QtWidgets.QLabel(self.transaction_3)
        self.amount_3.setObjectName("amount_3")
        self.horizontalLayout_20.addWidget(self.amount_3)
        self.details_3 = QtWidgets.QFrame(self.transaction_3)
        self.details_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.details_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.details_3.setObjectName("details_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.details_3)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.withdraw_3 = QtWidgets.QLabel(self.details_3)
        self.withdraw_3.setObjectName("withdraw_3")
        self.verticalLayout_26.addWidget(self.withdraw_3)
        self.date_3 = QtWidgets.QLabel(self.details_3)
        self.date_3.setObjectName("date_3")
        self.verticalLayout_26.addWidget(self.date_3)
        self.horizontalLayout_20.addWidget(self.details_3)
        self.verticalLayout_21.addWidget(self.transaction_3)
        self.verticalLayout_9.addWidget(self.transactions)